"""Generate so101_kinematics.py from mecanum_dualarm.usd (run locally with usd-core).

    uv run --python 3.12 --with usd-core python gen_so101_kinematics.py
"""
import os

from pxr import Gf, Usd, UsdGeom, UsdPhysics

ROOT = os.path.dirname(os.path.abspath(__file__))
SCENE = os.path.join(ROOT, "chem_lab_scene.usda")
OUT = os.path.join(ROOT, "so101_kinematics.py")
JOINTS = ["Rotation", "Pitch", "Elbow", "Wrist_Pitch", "Wrist_Roll"]
ARMS = {"L": "/so101_new_calib", "R": "/so101_new_calib_0"}
AX = {"X": Gf.Vec3d(1, 0, 0), "Y": Gf.Vec3d(0, 1, 0), "Z": Gf.Vec3d(0, 0, 1)}

st = Usd.Stage.Open(SCENE, Usd.Stage.LoadNone)
xc = UsdGeom.XformCache()
bc = UsdGeom.BBoxCache(Usd.TimeCode.Default(), ["default", "render"])
base_inv = xc.GetLocalToWorldTransform(st.GetPrimAtPath("/moebius_mecanum_base/base_link")).GetInverse()


def r6(v):
    return [round(float(c), 6) for c in v]


arms = {}
for side, root in ARMS.items():
    axes, points, limits = [], [], []
    for j in JOINTS:
        jt = UsdPhysics.RevoluteJoint(st.GetPrimAtPath(f"{root}/joints/{side}_{j}"))
        body1 = xc.GetLocalToWorldTransform(st.GetPrimAtPath(jt.GetBody1Rel().GetTargets()[0]))
        axis = Gf.Rotation(Gf.Quatd(jt.GetLocalRot1Attr().Get())).TransformDir(AX[jt.GetAxisAttr().Get()])
        w = base_inv.TransformDir(body1.TransformDir(axis)).GetNormalized()
        q = base_inv.Transform(body1.Transform(Gf.Vec3d(jt.GetLocalPos1Attr().Get())))
        axes.append(r6(w))
        points.append(r6(q))
        limits.append([round(jt.GetLowerLimitAttr().Get(), 3), round(jt.GetUpperLimitAttr().Get(), 3)])
    g = bc.ComputeWorldBound(st.GetPrimAtPath(f"{root}/gripper")).ComputeAlignedRange().GetMidpoint()
    jw = bc.ComputeWorldBound(st.GetPrimAtPath(f"{root}/jaw")).ComputeAlignedRange().GetMidpoint()
    tool0 = (base_inv.Transform(g) + base_inv.Transform(jw)) / 2
    arms[side] = {"axes": axes, "points": points, "limits_deg": limits, "tool0": r6(tool0)}

body = f'''"""SO-101 dual-arm position kinematics on the mecanum base.

GENERATED by gen_so101_kinematics.py from chem_lab_scene.usda — do not edit by hand.

Frame: base_link (+X forward, +Y left, +Z up; base_link is 0.101 m above the floor).
Zero config = the pose stored in the USD (all arm joints 0 rad).
Product of exponentials over {JOINTS}.
Joint i rotates about unit axis `axes[i]` through point `points[i]` (both in base_link, zero config).
TOOL0 = midpoint of the gripper and jaw bounding-box centres (rough grasp point).
Only numpy is needed (runs in the isaac_ros env).
"""
import math

import numpy as np

JOINTS = {JOINTS!r}
ARMS = {arms!r}

SEEDS = [
    np.zeros(5),
    np.array([0.0, 0.8, -0.8, 0.8, 0.0]),
    np.array([0.0, 1.2, -1.0, 1.2, 0.0]),
    np.array([0.0, 1.5, -0.7, 0.6, 0.0]),
]


def joint_names(side):
    return [f"{{side}}_{{j}}" for j in JOINTS]


def _exp(w, q, th):
    w = np.asarray(w, float)
    q = np.asarray(q, float)
    k = np.array([[0, -w[2], w[1]], [w[2], 0, -w[0]], [-w[1], w[0], 0]])
    rot = np.eye(3) + math.sin(th) * k + (1 - math.cos(th)) * k @ k
    t = np.eye(4)
    t[:3, :3] = rot
    t[:3, 3] = (np.eye(3) - rot) @ q
    return t


def fk(side, th):
    """Tool point in base_link for joint angles th (rad, order JOINTS)."""
    arm = ARMS[side]
    t = np.eye(4)
    for w, q, a in zip(arm["axes"], arm["points"], th):
        t = t @ _exp(w, q, a)
    return (t @ np.append(np.asarray(arm["tool0"], float), 1.0))[:3]


def limits(side):
    lim = np.radians(np.array(ARMS[side]["limits_deg"], float))
    return lim[:, 0], lim[:, 1]


def ik(side, target, seed=None, iters=300, tol=1e-4, damping=0.02):
    """Damped least squares, joint limits clamped. Returns (theta, position error m)."""
    lo, hi = limits(side)
    th = np.zeros(5) if seed is None else np.clip(np.asarray(seed, float), lo, hi)
    target = np.asarray(target, float)
    for _ in range(iters):
        p = fk(side, th)
        e = target - p
        if np.linalg.norm(e) < tol:
            break
        jac = np.zeros((3, 5))
        for i in range(5):
            d = np.zeros(5)
            d[i] = 1e-5
            jac[:, i] = (fk(side, th + d) - p) / 1e-5
        step = jac.T @ np.linalg.solve(jac @ jac.T + damping * damping * np.eye(3), e)
        th = np.clip(th + step, lo, hi)
    return th, float(np.linalg.norm(target - fk(side, th)))


def ik_best(side, target, seeds=None):
    """Try several seeds, return the lowest-error solution (theta, err)."""
    tries = [ik(side, target, s) for s in (seeds if seeds is not None else SEEDS)]
    return min(tries, key=lambda r: r[1])
'''
with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
    fh.write(body)
print("wrote", OUT)
for side, a in arms.items():
    print(side, "tool0", a["tool0"], "Pitch point", a["points"][1])
