"""Generate so101_kinematics.py from chem_lab_scene.usda (run locally with usd-core).

    uv run --python 3.12 --with usd-core --with numpy python gen_so101_kinematics.py
"""
import os

import numpy as np
from pxr import Gf, Usd, UsdGeom, UsdPhysics

ROOT = os.path.dirname(os.path.abspath(__file__))
SCENE = os.path.join(ROOT, "chem_lab_scene.usda")
OUT = os.path.join(ROOT, "so101_kinematics.py")
JOINTS = ["Rotation", "Pitch", "Elbow", "Wrist_Pitch", "Wrist_Roll"]
ARMS = {"L": "/so101_new_calib", "R": "/so101_new_calib_0"}
AX = {"X": Gf.Vec3d(1, 0, 0), "Y": Gf.Vec3d(0, 1, 0), "Z": Gf.Vec3d(0, 0, 1)}
FIXED_FINGER = "gripper/visuals/wrist_roll_follower_so101_v1"
MOVING_JAW = "jaw/visuals/moving_jaw_so101_v1"
TIP_LEN = 0.02      # finger tip region used to find the pinch point, m

st = Usd.Stage.Open(SCENE)
xc = UsdGeom.XformCache()
bc = UsdGeom.BBoxCache(Usd.TimeCode.Default(), ["default", "render"])
base_inv = xc.GetLocalToWorldTransform(st.GetPrimAtPath("/moebius_mecanum_base/base_link")).GetInverse()
base_inv_np = np.array(base_inv).T


def r6(v):
    return [round(float(c), 6) for c in v]


def joint(root, name):
    jt = UsdPhysics.RevoluteJoint(st.GetPrimAtPath(f"{root}/joints/{name}"))
    body1 = xc.GetLocalToWorldTransform(st.GetPrimAtPath(jt.GetBody1Rel().GetTargets()[0]))
    axis = Gf.Rotation(Gf.Quatd(jt.GetLocalRot1Attr().Get())).TransformDir(AX[jt.GetAxisAttr().Get()])
    w = base_inv.TransformDir(body1.TransformDir(axis)).GetNormalized()
    q = base_inv.Transform(body1.Transform(Gf.Vec3d(jt.GetLocalPos1Attr().Get())))
    return r6(w), r6(q), [round(jt.GetLowerLimitAttr().Get(), 3), round(jt.GetUpperLimitAttr().Get(), 3)]


def mesh_points(root, rel):
    """All mesh points under root/rel in base_link (instance proxies included)."""
    out = []
    for p in Usd.PrimRange(st.GetPrimAtPath(f"{root}/{rel}"), Usd.TraverseInstanceProxies()):
        if not p.IsA(UsdGeom.Mesh):
            continue
        pts = np.array(UsdGeom.Mesh(p).GetPointsAttr().Get(), float)
        m = base_inv_np @ np.array(xc.GetLocalToWorldTransform(p)).T
        out.append((m @ np.c_[pts, np.ones(len(pts))].T).T[:, :3])
    return np.vstack(out)


arms = {}
for side, root in ARMS.items():
    axes, points, limits = [], [], []
    for j in JOINTS:
        w, q, lim = joint(root, f"{side}_{j}")
        axes.append(w)
        points.append(q)
        limits.append(lim)
    g = bc.ComputeWorldBound(st.GetPrimAtPath(f"{root}/gripper")).ComputeAlignedRange().GetMidpoint()
    jw = bc.ComputeWorldBound(st.GetPrimAtPath(f"{root}/jaw")).ComputeAlignedRange().GetMidpoint()
    tool0 = (base_inv.Transform(g) + base_inv.Transform(jw)) / 2
    jaw_axis, jaw_point, jaw_limits = joint(root, f"{side}_Jaw")

    # zero config: the gripper points +X, the fixed finger is below and the moving jaw above (opens +Z)
    ff, mj = mesh_points(root, FIXED_FINGER), mesh_points(root, MOVING_JAW)
    tip_x = ff[:, 0].max()
    ff_tip = ff[ff[:, 0] > tip_x - TIP_LEN]
    mj_tip = mj[mj[:, 0] > tip_x - TIP_LEN]
    if not (mj_tip[:, 2].min() > ff_tip[:, 2].max()):
        raise RuntimeError(f"{side}: jaw is not above the fixed finger at zero config")
    pinch0 = [tip_x - TIP_LEN / 2, ff_tip[:, 1].mean(), (ff_tip[:, 2].max() + mj_tip[:, 2].min()) / 2]
    arms[side] = {"axes": axes, "points": points, "limits_deg": limits, "tool0": r6(tool0),
                  "jaw_axis": jaw_axis, "jaw_point": jaw_point, "jaw_limits_deg": jaw_limits,
                  "pinch0": r6(pinch0), "finger_tip_x0": round(float(tip_x), 6),
                  "jaw_gap0": round(float(mj_tip[:, 2].min() - ff_tip[:, 2].max()), 6)}

body = f'''"""SO-101 dual-arm kinematics on the mecanum base.

GENERATED by gen_so101_kinematics.py from chem_lab_scene.usda — do not edit by hand.

Frame: base_link (+X forward, +Y left, +Z up; base_link is 0.101 m above the floor).
Zero config = the pose stored in the USD (all arm joints 0 rad).
Product of exponentials over {JOINTS}.
Joint i rotates about unit axis `axes[i]` through point `points[i]` (both in base_link, zero config).
TOOL0  = midpoint of the gripper and jaw bounding-box centres (rough grasp point).
PINCH0 = point between the fixed finger and the moving jaw near the tips.
Gripper frame at zero config: pointing direction +X, jaw opening direction +Z (Jaw + = open).
Only numpy is needed (runs in the isaac_ros env).
"""
import math

import numpy as np

JOINTS = {JOINTS!r}
ARMS = {arms!r}

SEEDS = [
    np.zeros(5),
    np.array([0.0, 0.8, -0.8, 0.8, 0.0]),
    np.array([0.0, 1.2, -1.0, 1.2, 0.0]),
    np.array([0.0, 1.5, -0.7, 0.6, 0.0]),
]


def joint_names(side):
    return [f"{{side}}_{{j}}" for j in JOINTS]


def _exp(w, q, th):
    w = np.asarray(w, float)
    q = np.asarray(q, float)
    k = np.array([[0, -w[2], w[1]], [w[2], 0, -w[0]], [-w[1], w[0], 0]])
    rot = np.eye(3) + math.sin(th) * k + (1 - math.cos(th)) * k @ k
    t = np.eye(4)
    t[:3, :3] = rot
    t[:3, 3] = (np.eye(3) - rot) @ q
    return t


def fk_T(side, th):
    """4x4 motion of the gripper link relative to zero config, in base_link."""
    arm = ARMS[side]
    t = np.eye(4)
    for w, q, a in zip(arm["axes"], arm["points"], th):
        t = t @ _exp(w, q, a)
    return t


def fk(side, th):
    """Tool point in base_link for joint angles th (rad, order JOINTS)."""
    return (fk_T(side, th) @ np.append(np.asarray(ARMS[side]["tool0"], float), 1.0))[:3]


def grip_frame(side, th):
    """(pinch point, pointing direction, jaw opening direction) in base_link."""
    t = fk_T(side, th)
    return (t @ np.append(np.asarray(ARMS[side]["pinch0"], float), 1.0))[:3], t[:3, 0], t[:3, 2]


def limits(side):
    lim = np.radians(np.array(ARMS[side]["limits_deg"], float))
    return lim[:, 0], lim[:, 1]


def ik(side, target, seed=None, iters=300, tol=1e-4, damping=0.02):
    """Damped least squares, joint limits clamped. Returns (theta, position error m)."""
    lo, hi = limits(side)
    th = np.zeros(5) if seed is None else np.clip(np.asarray(seed, float), lo, hi)
    target = np.asarray(target, float)
    for _ in range(iters):
        p = fk(side, th)
        e = target - p
        if np.linalg.norm(e) < tol:
            break
        jac = np.zeros((3, 5))
        for i in range(5):
            d = np.zeros(5)
            d[i] = 1e-5
            jac[:, i] = (fk(side, th + d) - p) / 1e-5
        step = jac.T @ np.linalg.solve(jac @ jac.T + damping * damping * np.eye(3), e)
        th = np.clip(th + step, lo, hi)
    return th, float(np.linalg.norm(target - fk(side, th)))


def ik_best(side, target, seeds=None):
    """Try several seeds. Among solutions within 1 mm, return the one closest to the first seed
    (keeps the arm on the same elbow branch between stages); otherwise the lowest-error one."""
    seeds = list(seeds if seeds is not None else SEEDS)
    tries = [ik(side, target, s) for s in seeds]
    good = [r for r in tries if r[1] < 1e-3]
    if good:
        return min(good, key=lambda r: float(np.abs(r[0] - np.asarray(seeds[0], float)).max()))
    return min(tries, key=lambda r: r[1])


ANG_W = 0.05   # m per rad: weight of orientation residuals against position


def _grip_residual(side, th, target, radial, tilt):
    """[pinch position error (3), pointing elevation off -tilt, opening dir off the radial plane]."""
    p, d, o = grip_frame(side, th)
    tangent = np.array([0.0, radial[2], -radial[1]])      # in the YZ plane, perpendicular to radial
    return np.concatenate([target - p, [-ANG_W * (d[2] + math.sin(tilt)), -ANG_W * float(o @ tangent)]])


def ik_grip(side, target, radial, seed=None, tilt=0.0, iters=400, damping=0.01):
    """Pinch point at target, gripper pointing down by `tilt` rad (0 = horizontal),
    jaw opening direction with no component along the rim tangent and toward +radial (unit, YZ plane).
    Returns (theta, position error m, orientation error deg)."""
    lo, hi = limits(side)
    th = np.zeros(5) if seed is None else np.clip(np.asarray(seed, float), lo, hi)
    target, radial = np.asarray(target, float), np.asarray(radial, float)
    for _ in range(iters):
        e = _grip_residual(side, th, target, radial, tilt)
        if np.linalg.norm(e) < 2e-5:
            break
        jac = np.zeros((5, 5))
        for i in range(5):
            dd = np.zeros(5)
            dd[i] = 1e-6
            jac[:, i] = (e - _grip_residual(side, th + dd, target, radial, tilt)) / 1e-6
        step = jac.T @ np.linalg.solve(jac @ jac.T + damping * damping * np.eye(5), e)
        th = np.clip(th + step, lo, hi)
    p, d, o = grip_frame(side, th)
    tangent = np.array([0.0, radial[2], -radial[1]])
    ang = max(abs(math.degrees(math.asin(np.clip(d[2], -1, 1)) + tilt)),   # asin(d_z) = -tilt when met
              abs(math.degrees(math.asin(np.clip(o @ tangent, -1, 1)))))
    if o @ radial <= 0:          # jaw opening inward: the fingers would be on the wrong sides of the wall
        ang = 180.0
    return th, float(np.linalg.norm(target - p)), ang


def ik_grip_best(side, target, radial, seeds=None, tilt=0.0):
    """Like ik_best for ik_grip: within 1 mm and 2 deg, closest to the first seed. Wrist roll seeds added."""
    seeds = [np.asarray(s, float) for s in (seeds if seeds is not None else SEEDS)]
    tries = []
    for s in seeds:
        for roll in (s[4], 0.0, 0.7, -0.7, 1.4, -1.4):
            v = s.copy()
            v[4] = roll
            tries.append(ik_grip(side, target, radial, v, tilt))
    good = [r for r in tries if r[1] < 1e-3 and r[2] < 2.0]
    if good:
        return min(good, key=lambda r: float(np.abs(r[0] - seeds[0]).max()))
    return min(tries, key=lambda r: r[1] + ANG_W * math.radians(r[2]))
'''
with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
    fh.write(body)
print("wrote", OUT)
for side, a in arms.items():
    print(side, "tool0", a["tool0"], "pinch0", a["pinch0"], "jaw gap0", a["jaw_gap0"],
          "jaw axis", a["jaw_axis"], "point", a["jaw_point"], "limits", a["jaw_limits_deg"])
