"""SO-101 dual-arm position kinematics on the mecanum base.

GENERATED by gen_so101_kinematics.py from chem_lab_scene.usda — do not edit by hand.

Frame: base_link (+X forward, +Y left, +Z up; base_link is 0.101 m above the floor).
Zero config = the pose stored in the USD (all arm joints 0 rad).
Product of exponentials over ['Rotation', 'Pitch', 'Elbow', 'Wrist_Pitch', 'Wrist_Roll'].
Joint i rotates about unit axis `axes[i]` through point `points[i]` (both in base_link, zero config).
TOOL0 = midpoint of the gripper and jaw bounding-box centres (rough grasp point).
Only numpy is needed (runs in the isaac_ros env).
"""
import math

import numpy as np

JOINTS = ['Rotation', 'Pitch', 'Elbow', 'Wrist_Pitch', 'Wrist_Roll']
ARMS = {'L': {'axes': [[0.0, -3e-06, -1.0], [-1e-05, 1.0, -3e-06], [-9e-06, 1.0, -3e-06], [-9e-06, 1.0, -3e-06], [-0.99999, -1.3e-05, 0.004418]], 'points': [[0.123075, 0.100791, 0.104882], [0.153474, 0.082514, 0.159082], [0.181846, 0.082514, 0.271559], [0.316766, 0.082515, 0.276189], [0.377866, 0.100616, 0.275919]], 'limits_deg': [[-110.0, 110.0], [-100.0, 100.0], [-100.0, 90.0], [-95.0, 95.0], [-160.0, 160.0]], 'tool0': [0.433461, 0.099567, 0.284047]}, 'R': {'axes': [[0.0, -3e-06, -1.0], [-1.1e-05, 1.0, -3e-06], [-1.1e-05, 1.0, -3e-06], [-1.1e-05, 1.0, -3e-06], [-0.99999, -1.4e-05, 0.004426]], 'points': [[0.123075, -0.101209, 0.104882], [0.153474, -0.119487, 0.159082], [0.181847, -0.119486, 0.271558], [0.316767, -0.119485, 0.276188], [0.377866, -0.101384, 0.275917]], 'limits_deg': [[-110.0, 110.0], [-100.0, 100.0], [-100.0, 90.0], [-95.0, 95.0], [-160.0, 160.0]], 'tool0': [0.433462, -0.102433, 0.284043]}}

SEEDS = [
    np.zeros(5),
    np.array([0.0, 0.8, -0.8, 0.8, 0.0]),
    np.array([0.0, 1.2, -1.0, 1.2, 0.0]),
    np.array([0.0, 1.5, -0.7, 0.6, 0.0]),
]


def joint_names(side):
    return [f"{side}_{j}" for j in JOINTS]


def _exp(w, q, th):
    w = np.asarray(w, float)
    q = np.asarray(q, float)
    k = np.array([[0, -w[2], w[1]], [w[2], 0, -w[0]], [-w[1], w[0], 0]])
    rot = np.eye(3) + math.sin(th) * k + (1 - math.cos(th)) * k @ k
    t = np.eye(4)
    t[:3, :3] = rot
    t[:3, 3] = (np.eye(3) - rot) @ q
    return t


def fk(side, th):
    """Tool point in base_link for joint angles th (rad, order JOINTS)."""
    arm = ARMS[side]
    t = np.eye(4)
    for w, q, a in zip(arm["axes"], arm["points"], th):
        t = t @ _exp(w, q, a)
    return (t @ np.append(np.asarray(arm["tool0"], float), 1.0))[:3]


def limits(side):
    lim = np.radians(np.array(ARMS[side]["limits_deg"], float))
    return lim[:, 0], lim[:, 1]


def ik(side, target, seed=None, iters=300, tol=1e-4, damping=0.02):
    """Damped least squares, joint limits clamped. Returns (theta, position error m)."""
    lo, hi = limits(side)
    th = np.zeros(5) if seed is None else np.clip(np.asarray(seed, float), lo, hi)
    target = np.asarray(target, float)
    for _ in range(iters):
        p = fk(side, th)
        e = target - p
        if np.linalg.norm(e) < tol:
            break
        jac = np.zeros((3, 5))
        for i in range(5):
            d = np.zeros(5)
            d[i] = 1e-5
            jac[:, i] = (fk(side, th + d) - p) / 1e-5
        step = jac.T @ np.linalg.solve(jac @ jac.T + damping * damping * np.eye(3), e)
        th = np.clip(th + step, lo, hi)
    return th, float(np.linalg.norm(target - fk(side, th)))


def ik_best(side, target, seeds=None):
    """Try several seeds, return the lowest-error solution (theta, err)."""
    tries = [ik(side, target, s) for s in (seeds if seeds is not None else SEEDS)]
    return min(tries, key=lambda r: r[1])
