"""SO-101 dual-arm kinematics on the mecanum base.

GENERATED by gen_so101_kinematics.py from chem_lab_scene.usda — do not edit by hand.

Frame: base_link (+X forward, +Y left, +Z up; base_link is 0.101 m above the floor).
Zero config = the pose stored in the USD (all arm joints 0 rad).
Product of exponentials over ['Rotation', 'Pitch', 'Elbow', 'Wrist_Pitch', 'Wrist_Roll'].
Joint i rotates about unit axis `axes[i]` through point `points[i]` (both in base_link, zero config).
TOOL0  = midpoint of the gripper and jaw bounding-box centres (rough grasp point).
PINCH0 = point between the fixed finger and the moving jaw near the tips.
Gripper frame at zero config: pointing direction +X, jaw opening direction +Z (Jaw + = open).
Only numpy is needed (runs in the isaac_ros env).
"""
import math

import numpy as np

JOINTS = ['Rotation', 'Pitch', 'Elbow', 'Wrist_Pitch', 'Wrist_Roll']
ARMS = {'L': {'axes': [[0.0, -3e-06, -1.0], [-1e-05, 1.0, -3e-06], [-9e-06, 1.0, -3e-06], [-9e-06, 1.0, -3e-06], [-0.99999, -1.3e-05, 0.004418]], 'points': [[0.123075, 0.100791, 0.104882], [0.153474, 0.082514, 0.159082], [0.181846, 0.082514, 0.271559], [0.316766, 0.082515, 0.276189], [0.377866, 0.100616, 0.275919]], 'limits_deg': [[-110.0, 110.0], [-100.0, 100.0], [-100.0, 90.0], [-95.0, 95.0], [-160.0, 160.0]], 'tool0': [0.433461, 0.099567, 0.284047], 'jaw_axis': [1.7e-05, -1.0, 9e-06], 'jaw_point': [0.401355, 0.119417, 0.296016], 'jaw_limits_deg': [-40.0, 100.0], 'pinch0': [0.472251, 0.100377, 0.27562], 'finger_tip_x0': 0.482251, 'jaw_gap0': 0.016035}, 'R': {'axes': [[0.0, -3e-06, -1.0], [-1.1e-05, 1.0, -3e-06], [-1.1e-05, 1.0, -3e-06], [-1.1e-05, 1.0, -3e-06], [-0.99999, -1.4e-05, 0.004426]], 'points': [[0.123075, -0.101209, 0.104882], [0.153474, -0.119487, 0.159082], [0.181847, -0.119486, 0.271558], [0.316767, -0.119485, 0.276188], [0.377866, -0.101384, 0.275917]], 'limits_deg': [[-110.0, 110.0], [-100.0, 100.0], [-100.0, 90.0], [-95.0, 95.0], [-160.0, 160.0]], 'tool0': [0.433462, -0.102433, 0.284043], 'jaw_axis': [1.8e-05, -1.0, 8e-06], 'jaw_point': [0.401355, -0.082584, 0.296013], 'jaw_limits_deg': [-40.0, 100.0], 'pinch0': [0.472251, -0.101623, 0.275614], 'finger_tip_x0': 0.482251, 'jaw_gap0': 0.016028}}

SEEDS = [
    np.zeros(5),
    np.array([0.0, 0.8, -0.8, 0.8, 0.0]),
    np.array([0.0, 1.2, -1.0, 1.2, 0.0]),
    np.array([0.0, 1.5, -0.7, 0.6, 0.0]),
]


def joint_names(side):
    return [f"{side}_{j}" for j in JOINTS]


def _exp(w, q, th):
    w = np.asarray(w, float)
    q = np.asarray(q, float)
    k = np.array([[0, -w[2], w[1]], [w[2], 0, -w[0]], [-w[1], w[0], 0]])
    rot = np.eye(3) + math.sin(th) * k + (1 - math.cos(th)) * k @ k
    t = np.eye(4)
    t[:3, :3] = rot
    t[:3, 3] = (np.eye(3) - rot) @ q
    return t


def fk_T(side, th):
    """4x4 motion of the gripper link relative to zero config, in base_link."""
    arm = ARMS[side]
    t = np.eye(4)
    for w, q, a in zip(arm["axes"], arm["points"], th):
        t = t @ _exp(w, q, a)
    return t


def fk(side, th):
    """Tool point in base_link for joint angles th (rad, order JOINTS)."""
    return (fk_T(side, th) @ np.append(np.asarray(ARMS[side]["tool0"], float), 1.0))[:3]


def grip_frame(side, th):
    """(pinch point, pointing direction, jaw opening direction) in base_link."""
    t = fk_T(side, th)
    return (t @ np.append(np.asarray(ARMS[side]["pinch0"], float), 1.0))[:3], t[:3, 0], t[:3, 2]


def limits(side):
    lim = np.radians(np.array(ARMS[side]["limits_deg"], float))
    return lim[:, 0], lim[:, 1]


def ik(side, target, seed=None, iters=300, tol=1e-4, damping=0.02):
    """Damped least squares, joint limits clamped. Returns (theta, position error m)."""
    lo, hi = limits(side)
    th = np.zeros(5) if seed is None else np.clip(np.asarray(seed, float), lo, hi)
    target = np.asarray(target, float)
    for _ in range(iters):
        p = fk(side, th)
        e = target - p
        if np.linalg.norm(e) < tol:
            break
        jac = np.zeros((3, 5))
        for i in range(5):
            d = np.zeros(5)
            d[i] = 1e-5
            jac[:, i] = (fk(side, th + d) - p) / 1e-5
        step = jac.T @ np.linalg.solve(jac @ jac.T + damping * damping * np.eye(3), e)
        th = np.clip(th + step, lo, hi)
    return th, float(np.linalg.norm(target - fk(side, th)))


def ik_best(side, target, seeds=None):
    """Try several seeds. Among solutions within 1 mm, return the one closest to the first seed
    (keeps the arm on the same elbow branch between stages); otherwise the lowest-error one."""
    seeds = list(seeds if seeds is not None else SEEDS)
    tries = [ik(side, target, s) for s in seeds]
    good = [r for r in tries if r[1] < 1e-3]
    if good:
        return min(good, key=lambda r: float(np.abs(r[0] - np.asarray(seeds[0], float)).max()))
    return min(tries, key=lambda r: r[1])


ANG_W = 0.05   # m per rad: weight of orientation residuals against position


def _grip_residual(side, th, target, radial, tilt):
    """[pinch position error (3), pointing elevation off -tilt, opening dir off the radial plane]."""
    p, d, o = grip_frame(side, th)
    tangent = np.array([0.0, radial[2], -radial[1]])      # in the YZ plane, perpendicular to radial
    return np.concatenate([target - p, [-ANG_W * (d[2] + math.sin(tilt)), -ANG_W * float(o @ tangent)]])


def ik_grip(side, target, radial, seed=None, tilt=0.0, iters=400, damping=0.01):
    """Pinch point at target, gripper pointing down by `tilt` rad (0 = horizontal),
    jaw opening direction with no component along the rim tangent and toward +radial (unit, YZ plane).
    Returns (theta, position error m, orientation error deg)."""
    lo, hi = limits(side)
    th = np.zeros(5) if seed is None else np.clip(np.asarray(seed, float), lo, hi)
    target, radial = np.asarray(target, float), np.asarray(radial, float)
    for _ in range(iters):
        e = _grip_residual(side, th, target, radial, tilt)
        if np.linalg.norm(e) < 2e-5:
            break
        jac = np.zeros((5, 5))
        for i in range(5):
            dd = np.zeros(5)
            dd[i] = 1e-6
            jac[:, i] = (e - _grip_residual(side, th + dd, target, radial, tilt)) / 1e-6
        step = jac.T @ np.linalg.solve(jac @ jac.T + damping * damping * np.eye(5), e)
        th = np.clip(th + step, lo, hi)
    p, d, o = grip_frame(side, th)
    tangent = np.array([0.0, radial[2], -radial[1]])
    ang = max(abs(math.degrees(math.asin(np.clip(d[2], -1, 1)) + tilt)),   # asin(d_z) = -tilt when met
              abs(math.degrees(math.asin(np.clip(o @ tangent, -1, 1)))))
    if o @ radial <= 0:          # jaw opening inward: the fingers would be on the wrong sides of the wall
        ang = 180.0
    return th, float(np.linalg.norm(target - p)), ang


def ik_grip_best(side, target, radial, seeds=None, tilt=0.0):
    """Like ik_best for ik_grip: within 1 mm and 2 deg, closest to the first seed. Wrist roll seeds added."""
    seeds = [np.asarray(s, float) for s in (seeds if seeds is not None else SEEDS)]
    tries = []
    for s in seeds:
        for roll in (s[4], 0.0, 0.7, -0.7, 1.4, -1.4):
            v = s.copy()
            v[4] = roll
            tries.append(ik_grip(side, target, radial, v, tilt))
    good = [r for r in tries if r[1] < 1e-3 and r[2] < 2.0]
    if good:
        return min(good, key=lambda r: float(np.abs(r[0] - seeds[0]).max()))
    return min(tries, key=lambda r: r[1] + ANG_W * math.radians(r[2]))
